import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Bell, Bot, Brain, Database, FileText, HeartPulse, Home, KeyRound, Link2, LogOut, MessageSquare, Moon, Play, RefreshCw, Rss, Search, Settings, Shield, Slack, Sun, Users } from "lucide-react";
import "./styles/app.css";

const store = { token: localStorage.getItem("jarvis_token") || "", csrf: localStorage.getItem("jarvis_csrf") || "" };
const headers = (json = true) => ({ ...(json ? { "Content-Type": "application/json" } : {}), ...(store.token ? { Authorization: `Bearer ${store.token}` } : {}), ...(store.csrf ? { "X-CSRF-Token": store.csrf } : {}) });
async function api(url, options = {}) {
  const res = await fetch(url, { ...options, headers: { ...headers(options.body !== undefined), ...(options.headers || {}) } });
  const text = await res.text();
  const data = text ? JSON.parse(text) : {};
  if (!res.ok) throw new Error(data.error || text || res.statusText);
  return data;
}
const Field = ({ label, children }) => <label className="field"><span>{label}</span>{children}</label>;
const Button = ({ icon: Icon, children, variant = "primary", ...props }) => <button className={`btn ${variant}`} {...props}>{Icon && <Icon size={16} />}{children}</button>;
const Metric = ({ icon: Icon, label, value }) => <article className="metric">{Icon && <Icon size={18}/>}<span>{label}</span><strong>{value ?? "-"}</strong></article>;
const Header = ({ eyebrow, title, actions }) => <header className="top"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div><div className="actions">{actions}</div></header>;
function Table({ rows, columns, empty = "No records" }) {
  return <div className="table-wrap"><table><thead><tr>{columns.map(c => <th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={r.id || i}>{columns.map(c => <td key={c.label}>{c.render ? c.render(r) : String(r[c.key] ?? "")}</td>)}</tr>) : <tr><td colSpan={columns.length}>{empty}</td></tr>}</tbody></table></div>;
}

function Login({ onLogin }) {
  const [username, setUsername] = useState("admin"), [password, setPassword] = useState(""), [error, setError] = useState("");
  async function submit(e) {
    e.preventDefault(); setError("");
    try {
      const d = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }).then(async r => { const b = await r.json(); if (!r.ok) throw new Error(b.error || "Login failed"); return b; });
      store.token = d.token; store.csrf = d.csrf; localStorage.setItem("jarvis_token", d.token); localStorage.setItem("jarvis_csrf", d.csrf); onLogin(d.user);
    } catch (e) { setError(e.message); }
  }
  return <main className="login-screen"><form className="login-panel" onSubmit={submit}><p className="eyebrow">Secure access</p><h1>JARVIS Login</h1><p className="muted">Fresh Docker installs use <code>admin</code> / <code>admin123!ChangeMe</code> and then require a new password.</p><Field label="Username"><input value={username} onChange={e=>setUsername(e.target.value)} /></Field><Field label="Password"><input value={password} onChange={e=>setPassword(e.target.value)} type="password" /></Field><Button icon={KeyRound}>Login</Button>{error && <p className="error">{error}</p>}</form></main>;
}

function PasswordChange({ onChanged }) {
  const [current, setCurrent] = useState(""), [next, setNext] = useState(""), [error, setError] = useState("");
  async function submit(e) { e.preventDefault(); try { const d = await api("/api/auth/change-password", { method: "POST", body: JSON.stringify({ current_password: current, new_password: next }) }); store.token = d.token; store.csrf = d.csrf; localStorage.setItem("jarvis_token", d.token); localStorage.setItem("jarvis_csrf", d.csrf); onChanged(d.user); } catch (e) { setError(e.message); } }
  return <main className="login-screen"><form className="login-panel" onSubmit={submit}><p className="eyebrow">First login</p><h1>Change Password</h1><Field label="Current password"><input type="password" value={current} onChange={e=>setCurrent(e.target.value)} /></Field><Field label="New password"><input type="password" value={next} onChange={e=>setNext(e.target.value)} /></Field><Button icon={Shield}>Save Password</Button>{error && <p className="error">{error}</p>}</form></main>;
}

function Shell({ mode, theme, setTheme, user, logout, children }) {
  const adminNav = [["dashboard", Home, "Dashboard"], ["sources", Rss, "Sources"], ["models", Brain, "Models"], ["users", Users, "Users"], ["integrations", Bell, "Integrations"], ["mcp", Link2, "MCP"], ["storage", Database, "Storage"], ["logs", FileText, "Logs"], ["health", HeartPulse, "Health"], ["settings", Settings, "Settings"]];
  const userNav = [["feed", Home, "Feed"], ["reports", FileText, "Reports"], ["assistant", Bot, "Assistant"], ["notifications", Bell, "Notifications"], ["preferences", Settings, "Preferences"]];
  const nav = mode === "admin" ? adminNav : userNav;
  return <main className="app-shell"><aside className="side"><div className="brand"><span>J</span><div><strong>JARVIS</strong><small>{mode === "admin" ? "Admin Control" : "Intelligence Console"}</small></div></div><nav className="nav">{nav.map(([id, Icon, label]) => <button key={id} className={(location.hash.slice(1)||nav[0][0])===id ? "active" : ""} onClick={()=>{location.hash=id; window.dispatchEvent(new Event("hashchange"));}}><Icon size={17}/>{label}</button>)}</nav><div className="side-foot"><button onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun size={16}/>:<Moon size={16}/>} {theme==="dark"?"Light":"Dark"}</button><button onClick={()=>{location.href=mode==="admin"?"/user#feed":"/admin#dashboard";}}>{mode==="admin"?"User Console":"Admin"}</button><button onClick={logout}><LogOut size={16}/> Logout</button><small>{user.username}</small></div></aside><section className="main">{children}</section></main>;
}

function Dashboard() {
  const [d, setD] = useState(null); const load = () => api("/api/admin/overview").then(setD).catch(console.error); useEffect(load, []);
  return <section><Header eyebrow="Control plane" title="Dashboard" actions={<><Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button><Button icon={Play} onClick={()=>api("/api/admin/run/cycle",{method:"POST"})}>Run Cycle</Button></>} /><div className="metric-grid"><Metric icon={Activity} label="Phase" value={d?.runtime?.phase}/><Metric icon={Brain} label="Processed" value={d?.telemetry?.total_processed||0}/><Metric icon={Rss} label="Sources" value={d?.sources}/><Metric icon={Users} label="Users" value={d?.users}/></div><pre className="code-panel">{JSON.stringify(d||{}, null, 2)}</pre></section>;
}
function Sources() {
  const [rows,setRows]=useState([]), [f,setF]=useState({name:"",url:"",category:"tech",enabled:true}); const load=()=>api("/api/admin/sources").then(d=>setRows(d.sources)); useEffect(load,[]);
  return <section><Header eyebrow="Collectors" title="Source Management" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>} /><div className="panel form-grid"><Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="URL"><input value={f.url} onChange={e=>setF({...f,url:e.target.value})}/></Field><Field label="Category"><input value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/> Enabled</label><Button icon={Rss} onClick={()=>api("/api/admin/sources",{method:"POST",body:JSON.stringify(f)}).then(load)}>Save</Button></div><Table rows={rows} columns={[{label:"Name",key:"name"},{label:"Category",key:"category"},{label:"Enabled",render:r=>r.enabled?"Yes":"No"},{label:"URL",render:r=><code>{r.url}</code>},{label:"Action",render:r=><Button variant="danger" onClick={()=>api(`/api/admin/sources/${r.id}`,{method:"DELETE"}).then(load)}>Delete</Button>}]} /></section>;
}
function Models() {
  const [rows,setRows]=useState([]), [f,setF]=useState({name:"",provider_type:"openai_compatible",model:"",base_url:"",api_key_env:"",min_interval:0,enabled:true}); const load=()=>api("/api/admin/models").then(d=>setRows(d.providers)); useEffect(load,[]);
  return <section><Header eyebrow="AI routing" title="AI Model Management" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>} /><div className="panel form-grid"><Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Type"><select value={f.provider_type} onChange={e=>setF({...f,provider_type:e.target.value})}><option>gemini</option><option>groq</option><option>ollama</option><option>openai_compatible</option></select></Field><Field label="Model"><input value={f.model} onChange={e=>setF({...f,model:e.target.value})}/></Field><Field label="Base URL"><input value={f.base_url} onChange={e=>setF({...f,base_url:e.target.value})}/></Field><Field label="API Key Env"><input value={f.api_key_env} onChange={e=>setF({...f,api_key_env:e.target.value})}/></Field><Field label="Min Interval"><input type="number" value={f.min_interval} onChange={e=>setF({...f,min_interval:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/> Enabled</label><Button icon={Brain} onClick={()=>api("/api/admin/models",{method:"POST",body:JSON.stringify(f)}).then(load)}>Save Provider</Button></div><Table rows={rows} columns={[{label:"Name",key:"name"},{label:"Type",key:"provider_type"},{label:"Model",key:"model"},{label:"Enabled",render:r=>r.enabled?"Yes":"No"},{label:"Blocked",key:"blocked_until"}]} /></section>;
}
function UsersPage(){const[rows,setRows]=useState([]),[f,setF]=useState({username:"",display_name:"",role:"user",password:"ChangeMe123!"});const load=()=>api("/api/admin/users").then(d=>setRows(d.users));useEffect(load,[]);return <section><Header eyebrow="Access" title="User Management" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="panel form-grid"><Field label="Username"><input value={f.username} onChange={e=>setF({...f,username:e.target.value})}/></Field><Field label="Display name"><input value={f.display_name} onChange={e=>setF({...f,display_name:e.target.value})}/></Field><Field label="Role"><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>user</option><option>admin</option></select></Field><Field label="Temporary password"><input value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></Field><Button icon={Users} onClick={()=>api("/api/admin/users",{method:"POST",body:JSON.stringify(f)}).then(load)}>Create User</Button></div><Table rows={rows} columns={[{label:"Username",key:"username"},{label:"Role",key:"role"},{label:"Must change",render:r=>r.must_change_password?"Yes":"No"},{label:"Active",render:r=>r.active?"Yes":"No"}]}/></section>}
function Channels({userMode=false}){const[rows,setRows]=useState([]),[f,setF]=useState({kind:"telegram",label:"",target:"",enabled:true});const base=userMode?"/api/user/notification-channels":"/api/admin/notification-channels";const load=()=>api(base).then(d=>setRows(d.channels));useEffect(load,[base]);const save=()=>api(base,{method:"POST",body:JSON.stringify({...f,secret:f.kind==="slack"?{webhook_url:f.target}:{chat_id:f.target}})}).then(load);return <section><Header eyebrow="Delivery" title={userMode?"Notifications":"Telegram / Slack Integrations"} actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="panel guide-grid"><div><h2>Setup Guide</h2><p>Telegram: message /start or add a chat ID. Slack: paste an incoming webhook. Channels remain active until disabled.</p></div><div className="form-grid"><Field label="Kind"><select value={f.kind} onChange={e=>setF({...f,kind:e.target.value})}><option>telegram</option><option>slack</option></select></Field><Field label="Label"><input value={f.label} onChange={e=>setF({...f,label:e.target.value})}/></Field><Field label={f.kind==="slack"?"Webhook URL":"Chat ID"}><input value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></Field><label className="check"><input type="checkbox" checked={f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/> Enabled</label><Button icon={f.kind==="slack"?Slack:Bell} onClick={save}>Save Channel</Button></div></div><Table rows={rows} columns={[{label:"Kind",key:"kind"},{label:"Label",key:"label"},{label:"Target",key:"target"},{label:"Enabled",render:r=>r.enabled?"Yes":"No"},{label:"Action",render:r=><Button variant="danger" onClick={()=>api(`${base}/${r.id}`,{method:"DELETE"}).then(load)}>Disable</Button>}]} /></section>}
function Mcp(){const[rows,setRows]=useState([]),[f,setF]=useState({name:"",transport:"http",endpoint:"",enabled:true,args:""});const load=()=>api("/api/admin/mcp").then(d=>setRows(d.servers));useEffect(load,[]);const save=()=>api("/api/admin/mcp",{method:"POST",body:JSON.stringify({...f,config:f.transport==="stdio"?{command:f.endpoint,args:f.args.split(" ").filter(Boolean),timeout_seconds:20}:{allow_private_network:false}})}).then(load);return <section><Header eyebrow="Tool context" title="MCP Servers" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="panel form-grid"><Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Transport"><select value={f.transport} onChange={e=>setF({...f,transport:e.target.value})}><option value="http">HTTP</option><option value="stdio">STDIN/STDOUT</option></select></Field><Field label={f.transport==="http"?"Endpoint":"Command"}><input value={f.endpoint} onChange={e=>setF({...f,endpoint:e.target.value})}/></Field>{f.transport==="stdio"&&<Field label="Args"><input value={f.args} onChange={e=>setF({...f,args:e.target.value})}/></Field>}<Button icon={Link2} onClick={save}>Save MCP</Button></div><Table rows={rows} columns={[{label:"Name",key:"name"},{label:"Transport",key:"transport"},{label:"Endpoint",key:"endpoint"},{label:"Enabled",render:r=>r.enabled?"Yes":"No"},{label:"Test",render:r=><Button onClick={()=>api(`/api/admin/mcp/${r.id}/test`,{method:"POST"}).then(d=>alert(d.ok?"MCP test passed":d.error))}>Test</Button>}]} /></section>}
function JsonPage({url,title,eyebrow}){const[d,setD]=useState(null);const load=()=>api(url).then(setD);useEffect(load,[url]);return <section><Header eyebrow={eyebrow} title={title} actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><pre className="code-panel">{JSON.stringify(d||{},null,2)}</pre></section>}
function Logs(){const[rows,setRows]=useState([]),[q,setQ]=useState(""),[level,setLevel]=useState("");const load=()=>api(`/api/admin/logs?limit=500&level=${level}&q=${encodeURIComponent(q)}`).then(d=>setRows(d.logs));useEffect(load,[]);return <section><Header eyebrow="Observability" title="Logs" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="toolbar"><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option><option>INFO</option><option>WARN</option><option>ERROR</option></select><input placeholder="Search logs" value={q} onChange={e=>setQ(e.target.value)}/><Button icon={Search} onClick={load}>Filter</Button></div><Table rows={rows} columns={[{label:"Time",key:"created_at"},{label:"Level",key:"level"},{label:"Component",key:"component"},{label:"Message",key:"message"}]}/></section>}
function Feed(){const[rows,setRows]=useState([]),[hours,setHours]=useState(72),[q,setQ]=useState("");const load=()=>api(`/api/user/feed?hours=${hours}&q=${encodeURIComponent(q)}`).then(d=>setRows(d.items));useEffect(load,[]);return <section><Header eyebrow="Intelligence" title="Feed" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="toolbar"><select value={hours} onChange={e=>setHours(e.target.value)}><option value="24">24h</option><option value="72">72h</option><option value="168">7d</option></select><input placeholder="Search intelligence" value={q} onChange={e=>setQ(e.target.value)}/><Button icon={Search} onClick={load}>Search</Button></div><Table rows={rows} columns={[{label:"Saved",key:"saved_at"},{label:"Severity",key:"severity"},{label:"Source",key:"source"},{label:"Title",render:r=><a href={r.link} target="_blank">{r.title}</a>}]} /></section>}
function Reports(){const[rows,setRows]=useState([]);const load=()=>api("/api/user/reports?days=30").then(d=>setRows(d.reports));useEffect(load,[]);return <section><Header eyebrow="Digest archive" title="Reports" actions={<Button icon={RefreshCw} variant="secondary" onClick={load}>Refresh</Button>}/><div className="report-list">{rows.map((r,i)=><article className="report" key={i}><p className="eyebrow">{r._legacy_path||"report"}</p><h2>{r.headline||r.day_headline||"Digest"}</h2><p>{r.strategic_note||r.day_summary||"Saved report"}</p></article>)}</div></section>}
function Assistant(){const[query,setQuery]=useState("Explain how to use JARVIS"),[answer,setAnswer]=useState("");const ask=()=>{setAnswer("Thinking...");api("/api/user/assistant",{method:"POST",body:JSON.stringify({query,hours:72})}).then(d=>setAnswer(d.answer)).catch(e=>setAnswer(e.message));};return <section><Header eyebrow="Built-in help" title="JARVIS Assistant"/><div className="assistant"><textarea value={query} onChange={e=>setQuery(e.target.value)}/><Button icon={MessageSquare} onClick={ask}>Ask JARVIS</Button><pre className="answer">{answer||"Ask about setup, errors, reports, integrations, MCP, or recent intelligence."}</pre></div></section>}
function Preferences(){const[p,setP]=useState({theme:"system",digest_window:"72"});useEffect(()=>{api("/api/user/preferences").then(d=>setP({...p,...d.preferences})).catch(()=>{})},[]);return <section><Header eyebrow="Account" title="Preferences"/><div className="panel form-grid"><Field label="Preferred theme"><select value={p.theme} onChange={e=>setP({...p,theme:e.target.value})}><option>system</option><option>dark</option><option>light</option></select></Field><Field label="Digest window hours"><input value={p.digest_window} onChange={e=>setP({...p,digest_window:e.target.value})}/></Field><Button icon={Settings} onClick={()=>api("/api/user/preferences",{method:"POST",body:JSON.stringify(p)})}>Save</Button></div></section>}

function App(){const[theme,setTheme]=useState(localStorage.getItem("jarvis_theme")||"dark"),[user,setUser]=useState(null),[route,setRoute]=useState(location.hash.slice(1)||(location.pathname.startsWith("/admin")?"dashboard":"feed"));const mode=location.pathname.startsWith("/admin")?"admin":"user";useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("jarvis_theme",theme)},[theme]);useEffect(()=>{const h=()=>setRoute(location.hash.slice(1)||(mode==="admin"?"dashboard":"feed"));window.addEventListener("hashchange",h);return()=>window.removeEventListener("hashchange",h)},[mode]);useEffect(()=>{if(store.token)api("/api/auth/me").then(d=>setUser(d.user)).catch(()=>setUser(null))},[]);const logout=()=>{localStorage.removeItem("jarvis_token");localStorage.removeItem("jarvis_csrf");store.token="";store.csrf="";setUser(null)};const page=useMemo(()=>mode==="admin"?({dashboard:<Dashboard/>,sources:<Sources/>,models:<Models/>,users:<UsersPage/>,integrations:<Channels/>,mcp:<Mcp/>,storage:<JsonPage url="/api/admin/system/storage" title="Storage Status" eyebrow="Persistence"/>,logs:<Logs/>,health:<JsonPage url="/api/admin/system/health" title="System Health" eyebrow="Runtime"/>,settings:<JsonPage url="/api/admin/migrations" title="Settings & Migrations" eyebrow="System"/>}[route]||<Dashboard/>):({feed:<Feed/>,reports:<Reports/>,assistant:<Assistant/>,notifications:<Channels userMode/>,preferences:<Preferences/>}[route]||<Feed/>),[route,mode]);if(!user)return <Login onLogin={setUser}/>;if(user.must_change_password)return <PasswordChange onChanged={setUser}/>;return <Shell mode={mode} theme={theme} setTheme={setTheme} user={user} logout={logout}>{page}</Shell>}

createRoot(document.getElementById("root")).render(<App />);
